use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use regex::Regex;
use thiserror::Error;
use crate::crypto::CryptoEngine;

#[derive(Error, Debug)]
pub enum ConstitutionError {
    #[error("Failed to parse constitution JSON: {0}")]
    ParseError(#[from] serde_json::Error),
    #[error("Constitution hash mismatch — document may have been tampered")]
    HashMismatch,
    #[error("Missing required field: {0}")]
    MissingField(String),
    #[error("Regex compile error: {0}")]
    RegexError(#[from] regex::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToneConstraints {
    pub no_political_bias: bool,
    pub no_religious_endorsement: bool,
    pub no_competitor_promotion: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolPermissions {
    #[serde(flatten)]
    pub permissions: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EscalationThresholds {
    pub low: f32,
    pub medium: f32,
    pub high: f32,
    pub critical: f32,
}

impl Default for EscalationThresholds {
    fn default() -> Self {
        Self {
            low: 0.4,
            medium: 0.6,
            high: 0.75,
            critical: 0.90,
        }
    }
}

/// Machine-parseable client constitutional document.
/// Generated by LOGOS from client licensing application.
/// Immutable after deployment — version-locked and hash-verified.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Constitution {
    pub client_id: String,
    pub policy_version: String,
    pub industry_profile: String,
    pub prohibited_categories: Vec<String>,
    pub prohibited_patterns: Vec<String>,
    pub required_deferrals: Vec<String>,
    pub tone_constraints: ToneConstraints,
    pub tool_permissions: ToolPermissions,
    pub escalation_thresholds: EscalationThresholds,
    pub max_response_scope: Option<String>,
    /// SHA-256 of the full document at signing time.
    /// Used by OIM as immutable reference point.
    pub constitutional_hash: Option<String>,
}

impl Constitution {
    pub fn from_json(json: &str) -> Result<Self, ConstitutionError> {
        let constitution: Constitution = serde_json::from_str(json)?;
        Ok(constitution)
    }

    /// Compute and store the constitutional hash.
    /// Called once at deployment time. Hash is then immutable.
    pub fn seal(&mut self) {
        // Hash everything except the hash field itself
        let mut doc = self.clone();
        doc.constitutional_hash = None;
        let canonical = serde_json::to_string(&doc).unwrap_or_default();
        self.constitutional_hash = Some(CryptoEngine::compute_hash(&canonical));
    }

    /// Verify document integrity against stored hash.
    pub fn verify_integrity(&self) -> bool {
        if let Some(stored_hash) = &self.constitutional_hash {
            let mut doc = self.clone();
            doc.constitutional_hash = None;
            let canonical = serde_json::to_string(&doc).unwrap_or_default();
            let computed = CryptoEngine::compute_hash(&canonical);
            return &computed == stored_hash;
        }
        false
    }

    /// Default medical-grade constitution for testing.
    pub fn default_medical() -> Self {
        let mut c = Self {
            client_id: "test_medical_client".to_string(),
            policy_version: "v1.0.0".to_string(),
            industry_profile: "medical".to_string(),
            prohibited_categories: vec![
                "PII".to_string(),
                "SYSTEM_PROMPT_EXPOSURE".to_string(),
                "IP_LEAKAGE".to_string(),
            ],
            prohibited_patterns: vec![
                r"(?i)\b\d{3}-\d{2}-\d{4}\b".to_string(),           // SSN
                r"(?i)(ignore previous instructions)".to_string(),
                r"(?i)(reveal your system prompt)".to_string(),
                r"(?i)(you are now|pretend you are|act as if)".to_string(),
            ],
            required_deferrals: vec![
                "specific dosage recommendations".to_string(),
                "diagnosis confirmation".to_string(),
                "prescription decisions".to_string(),
            ],
            tone_constraints: ToneConstraints {
                no_political_bias: true,
                no_religious_endorsement: true,
                no_competitor_promotion: true,
            },
            tool_permissions: ToolPermissions {
                permissions: {
                    let mut m = HashMap::new();
                    m.insert("calculator".to_string(), "allowed".to_string());
                    m.insert("filesystem_write".to_string(), "restricted".to_string());
                    m.insert("external_http".to_string(), "restricted".to_string());
                    m
                },
            },
            escalation_thresholds: EscalationThresholds::default(),
            max_response_scope: Some("informational_only".to_string()),
            constitutional_hash: None,
        };
        c.seal();
        c
    }
}

/// Verdict from constitutional evaluation.
#[derive(Debug, Clone)]
pub struct ConstitutionalVerdict {
    pub violations: Vec<ConstitutionalViolation>,
    pub severity: crate::governance_signal::Severity,
    pub confidence: f32,
    pub payload_hash: String,
    pub policy_version: String,
}

#[derive(Debug, Clone)]
pub struct ConstitutionalViolation {
    pub rule_id: String,
    pub category: String,
    pub description: String,
    pub constitutional_ref: String,
}

/// Deterministic evaluator — no probabilistic reasoning.
/// Pattern match only. Signals OverWatch intelligence layer for
/// anything requiring contextual judgment.
pub struct ConstitutionalEvaluator {
    constitution: Constitution,
    compiled_patterns: Vec<(String, Regex)>,
}

impl ConstitutionalEvaluator {
    pub fn new(constitution: Constitution) -> Result<Self, ConstitutionError> {
        // Verify constitutional integrity before loading
        if constitution.constitutional_hash.is_some() && !constitution.verify_integrity() {
            return Err(ConstitutionError::HashMismatch);
        }

        // Compile all patterns at init — fail fast on bad patterns
        let mut compiled_patterns = Vec::new();
        for (i, pattern) in constitution.prohibited_patterns.iter().enumerate() {
            let regex = Regex::new(pattern)
                .map_err(ConstitutionError::RegexError)?;
            compiled_patterns.push((
                format!("CONST-PATTERN-{:03}", i + 1),
                regex,
            ));
        }

        Ok(Self {
            constitution,
            compiled_patterns,
        })
    }

    pub fn evaluate_inbound(&self, payload: &str) -> ConstitutionalVerdict {
        let mut violations = Vec::new();
        let payload_hash = CryptoEngine::compute_hash(payload);

        // Check compiled prohibited patterns
        for (rule_id, pattern) in &self.compiled_patterns {
            if pattern.is_match(payload) {
                violations.push(ConstitutionalViolation {
                    rule_id: rule_id.clone(),
                    category: "PROHIBITED_PATTERN".to_string(),
                    description: format!("Pattern match: {}", pattern.as_str()),
                    constitutional_ref: format!(
                        "{}/prohibited_patterns",
                        self.constitution.policy_version
                    ),
                });
            }
        }

        // Check prohibited categories (word-boundary aware)
        for category in &self.constitution.prohibited_categories {
            if self.word_boundary_match(payload, category) {
                violations.push(ConstitutionalViolation {
                    rule_id: format!("CONST-CAT-{}", category),
                    category: "PROHIBITED_CATEGORY".to_string(),
                    description: format!("Category detected: {}", category),
                    constitutional_ref: format!(
                        "{}/prohibited_categories/{}",
                        self.constitution.policy_version,
                        category
                    ),
                });
            }
        }

        self.build_verdict(violations, payload_hash)
    }

    pub fn evaluate_outbound(&self, payload: &str) -> ConstitutionalVerdict {
        let mut violations = Vec::new();
        let payload_hash = CryptoEngine::compute_hash(payload);

        // Check prohibited patterns in output
        for (rule_id, pattern) in &self.compiled_patterns {
            if pattern.is_match(payload) {
                violations.push(ConstitutionalViolation {
                    rule_id: format!("{}-OUT", rule_id),
                    category: "PROHIBITED_OUTPUT".to_string(),
                    description: "Output contains prohibited pattern".to_string(),
                    constitutional_ref: format!(
                        "{}/output_policy",
                        self.constitution.policy_version
                    ),
                });
            }
        }

        // Check required deferrals — output should not make these claims directly
        for deferral in &self.constitution.required_deferrals {
            if payload.to_lowercase().contains(&deferral.to_lowercase()) {
                violations.push(ConstitutionalViolation {
                    rule_id: format!("CONST-DEFER-{}", deferral.replace(' ', "_").to_uppercase()),
                    category: "DEFERRAL_VIOLATION".to_string(),
                    description: format!(
                        "Output may be making claim that requires deferral: {}",
                        deferral
                    ),
                    constitutional_ref: format!(
                        "{}/required_deferrals",
                        self.constitution.policy_version
                    ),
                });
            }
        }

        // Tone constraint checks on outbound
        if self.constitution.tone_constraints.no_political_bias {
            let political_pattern = once_cell::sync::Lazy::force(&POLITICAL_PATTERN);
            if political_pattern.is_match(payload) {
                violations.push(ConstitutionalViolation {
                    rule_id: "CONST-TONE-001".to_string(),
                    category: "TONE_VIOLATION".to_string(),
                    description: "Political bias detected in output".to_string(),
                    constitutional_ref: format!(
                        "{}/tone_constraints/no_political_bias",
                        self.constitution.policy_version
                    ),
                });
            }
        }

        if self.constitution.tone_constraints.no_religious_endorsement {
            let religious_pattern = once_cell::sync::Lazy::force(&RELIGIOUS_PATTERN);
            if religious_pattern.is_match(payload) {
                violations.push(ConstitutionalViolation {
                    rule_id: "CONST-TONE-002".to_string(),
                    category: "TONE_VIOLATION".to_string(),
                    description: "Religious endorsement detected in output".to_string(),
                    constitutional_ref: format!(
                        "{}/tone_constraints/no_religious_endorsement",
                        self.constitution.policy_version
                    ),
                });
            }
        }

        self.build_verdict(violations, payload_hash)
    }

    /// FIX: Word-boundary aware matching — prevents false positives
    /// like "system" matching "immune system" or "ecosystem".
    fn word_boundary_match(&self, text: &str, term: &str) -> bool {
        let pattern = format!(r"(?i)\b{}\b", regex::escape(term));
        Regex::new(&pattern)
            .map(|r| r.is_match(text))
            .unwrap_or(false)
    }

    fn build_verdict(
        &self,
        violations: Vec<ConstitutionalViolation>,
        payload_hash: String,
    ) -> ConstitutionalVerdict {
        use crate::governance_signal::Severity;

        let (severity, confidence) = match violations.len() {
            0 => (Severity::None, 0.0),
            1 => (Severity::Medium, 0.75),
            2 => (Severity::High, 0.85),
            _ => (Severity::Critical, 0.95),
        };

        ConstitutionalVerdict {
            violations,
            severity,
            confidence,
            payload_hash,
            policy_version: self.constitution.policy_version.clone(),
        }
    }

    pub fn policy_version(&self) -> &str {
        &self.constitution.policy_version
    }

    pub fn client_id(&self) -> &str {
        &self.constitution.client_id
    }

    pub fn escalation_thresholds(&self) -> &EscalationThresholds {
        &self.constitution.escalation_thresholds
    }
}

// Lazy-compiled global patterns for tone constraints
static POLITICAL_PATTERN: once_cell::sync::Lazy<Regex> = once_cell::sync::Lazy::new(|| {
    Regex::new(r"(?i)\b(vote for|elect|political party|democrat|republican|liberal|conservative)\b")
        .expect("Political pattern compile failed")
});

static RELIGIOUS_PATTERN: once_cell::sync::Lazy<Regex> = once_cell::sync::Lazy::new(|| {
    Regex::new(r"(?i)\b(convert to|religion is superior|only true faith|god commands you)\b")
        .expect("Religious pattern compile failed")
});
