#!/usr/bin/env bash
# ============================================================
#  LOGOS ASF — One-Click Local Setup
#  BYOAPIKEY — Model-Agnostic — No inference costs to LOGOS
#  US Provisional Patent 63/953,447
# ============================================================
set -e

BOLD="\033[1m"; GREEN="\033[32m"; YELLOW="\033[33m"
RED="\033[31m"; CYAN="\033[36m"; RESET="\033[0m"

header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
ok()     { echo -e "  ${GREEN}✓${RESET} $1"; }
warn()   { echo -e "  ${YELLOW}!${RESET} $1"; }
fail()   { echo -e "  ${RED}✗${RESET} $1"; exit 1; }
ask()    { echo -e "  ${BOLD}$1${RESET}"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║        LOGOS AGENTIC SOFTWARE FIRM — SETUP                  ║${RESET}"
echo -e "${BOLD}║        Abigail CP-00  +  Sentinel OverWatch                 ║${RESET}"
echo -e "${BOLD}║        BYOAPIKEY — Model Agnostic                           ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${RESET}"
echo ""

# ── Prereq checks ─────────────────────────────────────────────────────────────
header "[ 1/5 ] Checking prerequisites..."

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install Docker Desktop: https://docs.docker.com/get-docker/"
ok "Docker found: $(docker --version | cut -d' ' -f3 | tr -d ',')"

docker info >/dev/null 2>&1 || fail "Docker daemon not running. Start Docker Desktop and retry."
ok "Docker daemon running"

command -v docker >/dev/null && docker compose version >/dev/null 2>&1 && ok "Docker Compose found" \
  || fail "Docker Compose not found. Install Docker Desktop (includes Compose)."

# ── Env file setup ────────────────────────────────────────────────────────────
header "[ 2/5 ] Environment configuration..."

if [ -f .abigail.env ]; then
  warn ".abigail.env already exists — skipping creation (delete it to reconfigure)"
else
  echo ""
  echo -e "  ${BOLD}Choose your LLM backend:${RESET}"
  echo "    1) Groq         — fast, free tier, Llama 4 Scout  (recommended)"
  echo "    2) Anthropic    — Claude Sonnet 4"
  echo "    3) Perplexity   — Sonar"
  echo "    4) Ollama       — local model, no API key needed"
  echo ""
  read -p "  Enter choice [1-4]: " BACKEND_CHOICE

  case "$BACKEND_CHOICE" in
    1) BACKEND="groq"
       read -p "  Groq API key (get free at console.groq.com): " API_KEY
       KEY_LINE="GROQ_API_KEY=$API_KEY"
       ;;
    2) BACKEND="anthropic"
       read -p "  Anthropic API key (console.anthropic.com): " API_KEY
       KEY_LINE="ANTHROPIC_API_KEY=$API_KEY"
       ;;
    3) BACKEND="perplexity"
       read -p "  Perplexity API key (perplexity.ai/settings): " API_KEY
       KEY_LINE="PERPLEXITY_API_KEY=$API_KEY"
       ;;
    4) BACKEND="ollama"
       KEY_LINE="OLLAMA_BASE_URL=http://host.docker.internal:11434"
       warn "Ollama selected — make sure Ollama is running locally with a model pulled"
       ;;
    *) fail "Invalid choice" ;;
  esac

  echo ""
  echo -e "  ${BOLD}Industry profile (affects Sentinel threat thresholds):${RESET}"
  echo "    1) consumer   — default"
  echo "    2) medical"
  echo "    3) finance"
  echo "    4) defense"
  read -p "  Enter choice [1-4, default=1]: " PROFILE_CHOICE
  case "$PROFILE_CHOICE" in
    2) PROFILE="medical" ;;
    3) PROFILE="finance" ;;
    4) PROFILE="defense" ;;
    *) PROFILE="consumer" ;;
  esac

  # Generate tokens
  ADMIN_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null \
    || openssl rand -base64 32 | tr -d '=/+' | head -c 44)
  DEMO_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null \
    || openssl rand -base64 32 | tr -d '=/+' | head -c 44)

  cat > .abigail.env << ENV
# LOGOS ASF — Generated by setup.sh
# NEVER commit this file. It is in .gitignore.
# Re-run setup.sh to reconfigure.

# ── Backend ───────────────────────────────────────────────────────────────────
ABIGAIL_BACKEND=$BACKEND

# ── API Key ───────────────────────────────────────────────────────────────────
$KEY_LINE

# ── Auth Tokens (auto-generated) ─────────────────────────────────────────────
ABIGAIL_ADMIN_TOKEN=$ADMIN_TOKEN
ABIGAIL_DEMO_TOKEN=$DEMO_TOKEN

# ── Sentinel Profile ──────────────────────────────────────────────────────────
SENTOW_INDUSTRY_PROFILE=$PROFILE
SENTOW_HAAP_DRS_CEILING=60

# ── Sentinel URL (set by docker-compose — do not change) ─────────────────────
# SENTINEL_URL=http://sentinel:8080
ENV

  ok ".abigail.env created with backend=$BACKEND profile=$PROFILE"
  ok "Admin token generated (see .abigail.env)"
fi

# Validate env has required fields
BACKEND_VAL=$(grep "^ABIGAIL_BACKEND=" .abigail.env | cut -d= -f2)
[ -z "$BACKEND_VAL" ] && fail "ABIGAIL_BACKEND not set in .abigail.env"

# Check API key presence for non-ollama backends
if [ "$BACKEND_VAL" != "ollama" ]; then
  KEY_PRESENT=false
  for KEY_NAME in GROQ_API_KEY ANTHROPIC_API_KEY PERPLEXITY_API_KEY; do
    VAL=$(grep "^${KEY_NAME}=" .abigail.env 2>/dev/null | cut -d= -f2)
    if [ -n "$VAL" ] && [ "$VAL" != "YOUR_${KEY_NAME}_HERE" ] && [ "$VAL" != "PLACEHOLDER" ]; then
      KEY_PRESENT=true
      ok "API key found: $KEY_NAME"
      break
    fi
  done
  $KEY_PRESENT || fail "No valid API key found in .abigail.env. Add GROQ_API_KEY, ANTHROPIC_API_KEY, or PERPLEXITY_API_KEY."
fi

# ── .gitignore guard ──────────────────────────────────────────────────────────
header "[ 3/5 ] Security checks..."

if ! grep -q "\.abigail\.env" .gitignore 2>/dev/null; then
  echo ".abigail.env" >> .gitignore
  ok ".abigail.env added to .gitignore"
else
  ok ".abigail.env already in .gitignore"
fi

if git status --short 2>/dev/null | grep -q ".abigail.env"; then
  warn ".abigail.env appears staged — removing from git tracking"
  git rm --cached .abigail.env 2>/dev/null || true
fi

# ── Build and launch ──────────────────────────────────────────────────────────
header "[ 4/5 ] Building and launching..."
echo ""
warn "First build compiles Rust governance spine — takes 2-4 minutes."
warn "Subsequent runs use Docker cache and start in ~10 seconds."
echo ""

docker compose --env-file .abigail.env down 2>/dev/null || true
docker compose --env-file .abigail.env up --build -d

# ── Health check ──────────────────────────────────────────────────────────────
header "[ 5/5 ] Waiting for services..."
echo ""

wait_for() {
  local URL=$1; local NAME=$2; local MAX=60; local COUNT=0
  while [ $COUNT -lt $MAX ]; do
    if curl -sf "$URL" >/dev/null 2>&1; then
      ok "$NAME is up"
      return 0
    fi
    COUNT=$((COUNT + 1))
    printf "  waiting for $NAME... ($COUNT/${MAX}s)\r"
    sleep 1
  done
  warn "$NAME did not respond in ${MAX}s — check: docker compose logs"
  return 1
}

wait_for "http://localhost:9091/health" "Sentinel OverWatch"
wait_for "http://localhost:7070/api/status" "Abigail CP-00"

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║  LOGOS ASF is running.                                       ║${RESET}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "  ${BOLD}Abigail CP-00     :${RESET}  http://localhost:7070"
echo -e "  ${BOLD}Sentinel OverWatch:${RESET}  http://localhost:9091/health"
echo -e "  ${BOLD}Dashboard         :${RESET}  http://localhost:7070"
echo ""

echo -e "  ${BOLD}Admin token       :${RESET}  Admin token generated and stored in .abigail.env"
echo ""
echo -e "  ${BOLD}Quick tests:${RESET}"
echo "    make test-public    — unauthenticated chat"
echo "    make test-admin     — admin mode"
echo "    make test-injection — should block"
echo "    make status         — health check"
echo "    make logs           — follow logs"
echo "    make down           — stop everything"
echo ""
echo -e "  ${YELLOW}BYOAPIKEY: You provide the inference key. LOGOS provides the governance.${RESET}"
echo ""
